@startuml
title Commonクラス図

enum Scene
{
	START
	GAME
	RESULT
}

enum Key
{
	NONE
	LEFT
	RIGHT
	SPACE
	LEFTANDSPACE
	RIGHTANDSPACE
}

class SceneManager
{
	- Scene nowScene
	+ void nextScene()
	+ Scene getNowScene()
}

class InputManager
{
	- Key nowKey
	- void setKey(Key key)
	- void update()
	+ Key getKey()
}

class ScoreManager
{
	- int score
	void init()
	+ void addScore(int score)
	+ int getScore()
}

Scene -- SceneManager
Key   -- InputManager
@enduml